### ISSUE TITLE
Getsnaphot and download the snapshot restore files

### ISSUE THREAD

**Issue by ranjeetdbausa** [jasonmimick/opsmtools#4]
Hello Jasonmimick,

I am trying to use your source code to get latest  backup snapshot and download the restore snapshot files.

I have run script likewise as below  ...

C:\Python27\Scripts>opsmtools.py --host https://XXX-zhns077.XX.xxxx.xxx:8443 --group xxxxxxfb7789472834cc91a0 --username ranjeet.singh@xxxxxxx.com --apikey xxxxxx35-2da3-43bf-8507-789ddc667e05 --clusterId xxxx5477894706343f7ef7  --getSnapshots
Traceback (most recent call last):
  File "C:\Python27\Scripts\opsmtools.py", line 727, in <module>
    parsed_args.action(parsed_args)
  File "C:\Python27\Scripts\opsmtools.py", line 35, in get_snapshots
    ,auth=HTTPDigestAuth(args.username,args.apikey))
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xxx-xxxxx.xxx.xxxx.xxx', port=8443): Max retries exceeded with url: /api/public/v1.0/groups/xxxxxfb7789472834cc91a0/clusters/xxxxxx5477894706343f7ef7/snapshots (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))

**Comment by jasonmimick** [comment]
This is due to an SSL cert verification failure.
Right now the code doesn't skip verification, so would need to fix by having right certs, or change code to allow ``verify=false`` see http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
Feel free to submit a pull to add an option to skip ssl verification.

**Comment by ranjeetdbausa** [comment]
Thanks for your reply .

I have used the CA files  with verify and its working . I really appreciate your effort on writing script.

Ranjeet Singh
